package com.luqta.app;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
 int pink=Color.rgb(255,55,150), cyan=Color.rgb(35,205,255), gold=Color.rgb(255,194,45), bg=Color.rgb(8,9,13), panel=Color.rgb(22,23,30); LinearLayout root,body;
 TextView t(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(sp);v.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);v.setPadding(16,12,16,12);if(bold)v.setTypeface(null,1);return v;}
 GradientDrawable box(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 public void onCreate(Bundle b){super.onCreate(b);showHome();}
 void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.setBackgroundColor(bg); ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(22,20,22,20);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));root.addView(nav());setContentView(root);}
 View logo(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER);TextView a=t("●",22,true);a.setTextColor(cyan);TextView x=t("⌜  لُقطة  ⌟",32,true);x.setTextColor(Color.WHITE);TextView z=t("●",22,true);z.setTextColor(pink);l.addView(a);l.addView(x);l.addView(z);return l;}
 void showHome(){base();body.addView(logo());TextView sub=t("كل ما تبحث عنه .. في لُقطة واحدة",16,false);sub.setGravity(Gravity.CENTER);sub.setTextColor(Color.LTGRAY);body.addView(sub);TextView search=t("🔎  وش تدور عليه؟                         📷",17,false);search.setBackground(box(panel,32));search.setOnClickListener(v->showResults("نتائج البحث"));body.addView(search,new LinearLayout.LayoutParams(-1,68));body.addView(t("اكتشف الأقسام",20,true));String[] cats={"👗  أزياء","📱  إلكترونيات","🏠  منزل ومطبخ","🚗  سيارات وقطع غيار","✨  جمال وعناية","⌚  ساعات ومجوهرات","🎮  ألعاب وهوايات","🏃  رياضة ولياقة","🧸  أطفال ورضع"};for(int i=0;i<cats.length;i+=2){LinearLayout r=new LinearLayout(this);for(int j=i;j<Math.min(i+2,cats.length);j++){TextView c=t(cats[j],16,true);c.setGravity(Gravity.CENTER);c.setBackground(box(panel,28));c.setOnClickListener(v->showResults(((TextView)v).getText().toString()));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,92,1);p.setMargins(6,6,6,6);r.addView(c,p);}body.addView(r);}TextView banner=t("لُقطة AI  ✦\nصوّر أي منتج… وخله علينا",21,true);banner.setGravity(Gravity.CENTER);GradientDrawable gd=box(Color.rgb(34,20,55),34);gd.setStroke(2,pink);banner.setBackground(gd);banner.setOnClickListener(v->showCamera());body.addView(banner,new LinearLayout.LayoutParams(-1,135));}
 void showCamera(){base();body.addView(logo());TextView title=t("صوّر اللي عجبك",24,true);title.setGravity(Gravity.CENTER);body.addView(title);TextView frame=t("\n\n\n        ┌                         ┐\n\n          وجّه الكاميرا للمنتج\n\n        └                         ┘\n\n\n",20,true);frame.setGravity(Gravity.CENTER);frame.setBackground(box(Color.rgb(14,15,20),36));body.addView(frame,new LinearLayout.LayoutParams(-1,430));TextView snap=t("◉",56,true);snap.setGravity(Gravity.CENTER);snap.setTextColor(pink);snap.setOnClickListener(v->showResults("لقطة من الكاميرا"));body.addView(snap);}
 void showResults(String q){base();body.addView(logo());body.addView(t("نتائج: "+q,22,true));body.addView(t("الأفضل لك أولاً • حتى لو ما عندنا عمولة",14,false));String[] names={"اختيار مطابق تقريبًا","سعر ممتاز","بديل قريب","خيار موثوق"};String[] stores={"نون","متجر محلي","Amazon","متجر متخصص"};String[] prices={"189 ر.س","249 ر.س","299 ر.س","159 ر.س"};for(int i=0;i<4;i++){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(18,14,18,14);card.setBackground(box(panel,28));TextView pic=t(i%2==0?"◈   صورة المنتج":"◇   صورة المنتج",28,true);pic.setGravity(Gravity.CENTER);pic.setTextColor(i%2==0?cyan:gold);card.addView(pic,new LinearLayout.LayoutParams(-1,125));card.addView(t(names[i],18,true));card.addView(t(stores[i]+"     ★ 4."+(9-i),14,false));TextView pr=t(prices[i]+"     ♡",19,true);pr.setTextColor(i%2==0?pink:Color.WHITE);card.addView(pr);TextView buy=t("عرض المنتج  ←",15,true);buy.setGravity(Gravity.CENTER);buy.setBackground(box(Color.rgb(45,46,58),24));card.addView(buy,new LinearLayout.LayoutParams(-1,55));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,8,0,8);body.addView(card,cp);}}
 View nav(){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(8,8,8,8);n.setBackgroundColor(Color.rgb(13,14,19));String[] x={"⌂\nالرئيسية","♡\nالمفضلة","◎\nصِدها لي","●\nحسابي"};for(String s:x){TextView v=t(s,13,false);v.setGravity(Gravity.CENTER);v.setOnClickListener(z->{if(((TextView)z).getText().toString().contains("الرئيسية"))showHome();else Toast.makeText(this,"قريبًا في النسخة التالية",Toast.LENGTH_SHORT).show();});n.addView(v,new LinearLayout.LayoutParams(0,70,1));}return n;}
}
